# Generated by Django 5.0.4 on 2024-05-10 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=models.TextField(
                blank=True,
                default="Hey, there! I'm writing on PyPress",
                max_length=200,
                null=True,
            ),
        ),
    ]
